// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: gigachatv1.proto

package gigachatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Перечисление возможных режимов вызовов функций.
// В зависимости от содержимого запроса, модель решает сгенерировать сообщение или вызвать функцию. Модель вызывает встроенные функции, если отсутствует массив `functions` с описанием пользовательских функций.
type FunctionCallPolicy_Mode int32

const (
	FunctionCallPolicy_undefined FunctionCallPolicy_Mode = 0
	// В авторежиме модель, основываясь на тексте сообщений, решает нужно ли генерировать аргументы для функций, описанных в массиве `functions`.
	// При этом, если массив содержит описание хотя бы одной пользовательской функции, модель не сможет вызвать встроенную функцию, несмотря на текст сообщения.
	FunctionCallPolicy_auto FunctionCallPolicy_Mode = 1
	// Модель не будет вызывать встроенные функции или генерировать аргументы для пользовательских функций, а просто сгенерирует ответ в соответствии с полученными сообщениями.
	FunctionCallPolicy_none FunctionCallPolicy_Mode = 2
	// Принудительная генерация аргументов для указанной функции. При принудительной генерации описание функции и ее аргументов нужно обязательно передавать в массиве `functions`.
	FunctionCallPolicy_forced FunctionCallPolicy_Mode = 3
)

// Enum value maps for FunctionCallPolicy_Mode.
var (
	FunctionCallPolicy_Mode_name = map[int32]string{
		0: "undefined",
		1: "auto",
		2: "none",
		3: "forced",
	}
	FunctionCallPolicy_Mode_value = map[string]int32{
		"undefined": 0,
		"auto":      1,
		"none":      2,
		"forced":    3,
	}
)

func (x FunctionCallPolicy_Mode) Enum() *FunctionCallPolicy_Mode {
	p := new(FunctionCallPolicy_Mode)
	*p = x
	return p
}

func (x FunctionCallPolicy_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionCallPolicy_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_gigachatv1_proto_enumTypes[0].Descriptor()
}

func (FunctionCallPolicy_Mode) Type() protoreflect.EnumType {
	return &file_gigachatv1_proto_enumTypes[0]
}

func (x FunctionCallPolicy_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Сообщение, на которое ответит модель.
type ChatRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Options  *ChatOptions           `protobuf:"bytes,1,opt,name=options,proto3"`
	xxx_hidden_Model    string                 `protobuf:"bytes,2,opt,name=model,proto3"`
	xxx_hidden_Messages *[]*Message            `protobuf:"bytes,3,rep,name=messages,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_gigachatv1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatRequest) GetOptions() *ChatOptions {
	if x != nil {
		return x.xxx_hidden_Options
	}
	return nil
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		if x.xxx_hidden_Messages != nil {
			return *x.xxx_hidden_Messages
		}
	}
	return nil
}

func (x *ChatRequest) SetOptions(v *ChatOptions) {
	x.xxx_hidden_Options = v
}

func (x *ChatRequest) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *ChatRequest) SetMessages(v []*Message) {
	x.xxx_hidden_Messages = &v
}

func (x *ChatRequest) HasOptions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Options != nil
}

func (x *ChatRequest) ClearOptions() {
	x.xxx_hidden_Options = nil
}

type ChatRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Параметры сообщения.
	Options *ChatOptions
	// [Модель](https://developers.sber.ru/docs/ru/gigachat/models/main), которая будет генерировать ответ.
	Model string
	// Массив сообщений. Передавайте сообщения с ролями user и assistant, чтобы сохранить контекст разговора с моделью.
	Messages []*Message
}

func (b0 ChatRequest_builder) Build() *ChatRequest {
	m0 := &ChatRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Options = b.Options
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_Messages = &b.Messages
	return m0
}

// Параметры запроса, которые учитываются при генерировании ответа.
type ChatOptions struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Temperature       float32                `protobuf:"fixed32,1,opt,name=temperature,proto3,oneof"`
	xxx_hidden_TopP              float32                `protobuf:"fixed32,2,opt,name=top_p,json=topP,proto3,oneof"`
	xxx_hidden_MaxTokens         int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3,oneof"`
	xxx_hidden_RepetitionPenalty float32                `protobuf:"fixed32,5,opt,name=repetition_penalty,json=repetitionPenalty,proto3,oneof"`
	xxx_hidden_UpdateInterval    float32                `protobuf:"fixed32,6,opt,name=update_interval,json=updateInterval,proto3,oneof"`
	xxx_hidden_Flags             []string               `protobuf:"bytes,7,rep,name=flags,proto3"`
	xxx_hidden_FunctionCall      *FunctionCallPolicy    `protobuf:"bytes,8,opt,name=function_call,json=functionCall,proto3"`
	xxx_hidden_Functions         *[]*Function           `protobuf:"bytes,9,rep,name=functions,proto3"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ChatOptions) Reset() {
	*x = ChatOptions{}
	mi := &file_gigachatv1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatOptions) ProtoMessage() {}

func (x *ChatOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatOptions) GetTemperature() float32 {
	if x != nil {
		return x.xxx_hidden_Temperature
	}
	return 0
}

func (x *ChatOptions) GetTopP() float32 {
	if x != nil {
		return x.xxx_hidden_TopP
	}
	return 0
}

func (x *ChatOptions) GetMaxTokens() int32 {
	if x != nil {
		return x.xxx_hidden_MaxTokens
	}
	return 0
}

func (x *ChatOptions) GetRepetitionPenalty() float32 {
	if x != nil {
		return x.xxx_hidden_RepetitionPenalty
	}
	return 0
}

func (x *ChatOptions) GetUpdateInterval() float32 {
	if x != nil {
		return x.xxx_hidden_UpdateInterval
	}
	return 0
}

func (x *ChatOptions) GetFlags() []string {
	if x != nil {
		return x.xxx_hidden_Flags
	}
	return nil
}

func (x *ChatOptions) GetFunctionCall() *FunctionCallPolicy {
	if x != nil {
		return x.xxx_hidden_FunctionCall
	}
	return nil
}

func (x *ChatOptions) GetFunctions() []*Function {
	if x != nil {
		if x.xxx_hidden_Functions != nil {
			return *x.xxx_hidden_Functions
		}
	}
	return nil
}

func (x *ChatOptions) SetTemperature(v float32) {
	x.xxx_hidden_Temperature = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *ChatOptions) SetTopP(v float32) {
	x.xxx_hidden_TopP = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *ChatOptions) SetMaxTokens(v int32) {
	x.xxx_hidden_MaxTokens = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *ChatOptions) SetRepetitionPenalty(v float32) {
	x.xxx_hidden_RepetitionPenalty = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *ChatOptions) SetUpdateInterval(v float32) {
	x.xxx_hidden_UpdateInterval = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *ChatOptions) SetFlags(v []string) {
	x.xxx_hidden_Flags = v
}

func (x *ChatOptions) SetFunctionCall(v *FunctionCallPolicy) {
	x.xxx_hidden_FunctionCall = v
}

func (x *ChatOptions) SetFunctions(v []*Function) {
	x.xxx_hidden_Functions = &v
}

func (x *ChatOptions) HasTemperature() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChatOptions) HasTopP() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ChatOptions) HasMaxTokens() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ChatOptions) HasRepetitionPenalty() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ChatOptions) HasUpdateInterval() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ChatOptions) HasFunctionCall() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FunctionCall != nil
}

func (x *ChatOptions) ClearTemperature() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Temperature = 0
}

func (x *ChatOptions) ClearTopP() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TopP = 0
}

func (x *ChatOptions) ClearMaxTokens() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MaxTokens = 0
}

func (x *ChatOptions) ClearRepetitionPenalty() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_RepetitionPenalty = 0
}

func (x *ChatOptions) ClearUpdateInterval() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_UpdateInterval = 0
}

func (x *ChatOptions) ClearFunctionCall() {
	x.xxx_hidden_FunctionCall = nil
}

type ChatOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// *
	// Температура выборки. Значение температуры должно быть больше ноля. Чем выше значение, тем более случайным будет ответ модели. При значениях температуры больше двух, набор токенов в ответе модели может отличаться избыточной случайностью.
	// Значение по умолчанию зависит от выбранной модели (поле `model`) и может изменяться с обновлениями модели.
	Temperature *float32
	// *
	// Параметр используется как альтернатива температуре (поле `temperature`). Задает вероятностную массу токенов, которые должна учитывать модель.
	// Так, если передать значение 0.1, модель будет учитывать только токены, чья вероятностная масса входит в верхние 10%.
	// Значение по умолчанию зависит от выбранной модели (поле `model`) и может изменяться с обновлениями модели.
	// Значение изменяется в диапазоне от 0 до 1 включительно.
	TopP *float32
	// Максимальное количество токенов, которые будут использованы для создания ответов. По умолчанию используется 2048 токенов.
	MaxTokens *int32
	// *
	// Количество повторений слов. Должно быть больше ноля. Возможные значения:
	// При значении от 0 до 1 модель будет повторять уже использованные слова.
	// Значение 1.0 — нейтральное значение.
	// При значении больше 1 модель будет стараться не повторять слова.
	// Значение по умолчанию зависит от выбранной модели (поле `model`) и может изменяться с обновлениями модели.
	RepetitionPenalty *float32
	// *
	// Параметр потокового режима (`"stream": "true"`).
	// Задает минимальный интервал в секундах, который проходит между отправкой токенов.
	// Например, если указать `1`, сообщения будут приходить каждую секунду, но размер каждого из них будет больше, так как за секунду накапливается много токенов.
	// По умолчанию 0.
	UpdateInterval *float32
	Flags          []string
	// *
	// Поле, которое отвечает за то, как GigaChat будет работать с функциями.
	// Может быть строкой или объектом.
	// Возможные режимы работы функций определяются в FunctionCallPolicy
	FunctionCall *FunctionCallPolicy
	// Массив с описанием пользовательских функций.
	Functions []*Function
}

func (b0 ChatOptions_builder) Build() *ChatOptions {
	m0 := &ChatOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Temperature != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Temperature = *b.Temperature
	}
	if b.TopP != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_TopP = *b.TopP
	}
	if b.MaxTokens != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_MaxTokens = *b.MaxTokens
	}
	if b.RepetitionPenalty != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_RepetitionPenalty = *b.RepetitionPenalty
	}
	if b.UpdateInterval != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_UpdateInterval = *b.UpdateInterval
	}
	x.xxx_hidden_Flags = b.Flags
	x.xxx_hidden_FunctionCall = b.FunctionCall
	x.xxx_hidden_Functions = &b.Functions
	return m0
}

// Режимы работы пользовательских функций.
type FunctionCallPolicy struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Mode        FunctionCallPolicy_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=gigachat.v1.FunctionCallPolicy_Mode"`
	xxx_hidden_Name        *string                 `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FunctionCallPolicy) Reset() {
	*x = FunctionCallPolicy{}
	mi := &file_gigachatv1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallPolicy) ProtoMessage() {}

func (x *FunctionCallPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FunctionCallPolicy) GetMode() FunctionCallPolicy_Mode {
	if x != nil {
		return x.xxx_hidden_Mode
	}
	return FunctionCallPolicy_undefined
}

func (x *FunctionCallPolicy) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *FunctionCallPolicy) SetMode(v FunctionCallPolicy_Mode) {
	x.xxx_hidden_Mode = v
}

func (x *FunctionCallPolicy) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *FunctionCallPolicy) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FunctionCallPolicy) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

type FunctionCallPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Выбранный режим работы функции.
	Mode FunctionCallPolicy_Mode
	// Название пользовательской функции, для которой нужно сгенерировать аргументы.
	Name *string
}

func (b0 FunctionCallPolicy_builder) Build() *FunctionCallPolicy {
	m0 := &FunctionCallPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Mode = b.Mode
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

// Описание пользовательской функции.
type Function struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name             string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Description      string                 `protobuf:"bytes,2,opt,name=description,proto3"`
	xxx_hidden_Parameters       string                 `protobuf:"bytes,3,opt,name=parameters,proto3"`
	xxx_hidden_FewShotExamples  *[]*AnyExample         `protobuf:"bytes,4,rep,name=few_shot_examples,json=fewShotExamples,proto3"`
	xxx_hidden_ReturnParameters *string                `protobuf:"bytes,5,opt,name=return_parameters,json=returnParameters,proto3,oneof"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_gigachatv1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Function) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Function) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Function) GetParameters() string {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return ""
}

func (x *Function) GetFewShotExamples() []*AnyExample {
	if x != nil {
		if x.xxx_hidden_FewShotExamples != nil {
			return *x.xxx_hidden_FewShotExamples
		}
	}
	return nil
}

func (x *Function) GetReturnParameters() string {
	if x != nil {
		if x.xxx_hidden_ReturnParameters != nil {
			return *x.xxx_hidden_ReturnParameters
		}
		return ""
	}
	return ""
}

func (x *Function) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Function) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Function) SetParameters(v string) {
	x.xxx_hidden_Parameters = v
}

func (x *Function) SetFewShotExamples(v []*AnyExample) {
	x.xxx_hidden_FewShotExamples = &v
}

func (x *Function) SetReturnParameters(v string) {
	x.xxx_hidden_ReturnParameters = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Function) HasReturnParameters() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Function) ClearReturnParameters() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ReturnParameters = nil
}

type Function_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Название пользовательской функции, для которой будут сгенерированы аргументы.
	Name string
	// Текстовое описание функции.
	Description string
	// Валидный JSON-объект с набором пар `ключ-значение`, которые описывают аргументы функции.
	Parameters string
	// Массив примеров работы функции в виде объекта с парами `запрос_пользователя`—`параметры_функции`, которые будут служить модели примерами ожидаемого результата.
	FewShotExamples []*AnyExample
	// JSON-объект с описанием параметров, которые может вернуть ваша функция.
	ReturnParameters *string
}

func (b0 Function_builder) Build() *Function {
	m0 := &Function{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Parameters = b.Parameters
	x.xxx_hidden_FewShotExamples = &b.FewShotExamples
	if b.ReturnParameters != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_ReturnParameters = b.ReturnParameters
	}
	return m0
}

// Описание примера работы функции.
type AnyExample struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Request string                 `protobuf:"bytes,1,opt,name=request,proto3"`
	xxx_hidden_Params  *Params                `protobuf:"bytes,2,opt,name=params,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnyExample) Reset() {
	*x = AnyExample{}
	mi := &file_gigachatv1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyExample) ProtoMessage() {}

func (x *AnyExample) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AnyExample) GetRequest() string {
	if x != nil {
		return x.xxx_hidden_Request
	}
	return ""
}

func (x *AnyExample) GetParams() *Params {
	if x != nil {
		return x.xxx_hidden_Params
	}
	return nil
}

func (x *AnyExample) SetRequest(v string) {
	x.xxx_hidden_Request = v
}

func (x *AnyExample) SetParams(v *Params) {
	x.xxx_hidden_Params = v
}

func (x *AnyExample) HasParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Params != nil
}

func (x *AnyExample) ClearParams() {
	x.xxx_hidden_Params = nil
}

type AnyExample_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Запрос пользователя
	Request string
	// Массив примеров заполнения параметров пользовательской функции.
	Params *Params
}

func (b0 AnyExample_builder) Build() *AnyExample {
	m0 := &AnyExample{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Request = b.Request
	x.xxx_hidden_Params = b.Params
	return m0
}

// Массив параметров пользовательской функции.
type Params struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pairs *[]*Pair               `protobuf:"bytes,1,rep,name=pairs,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_gigachatv1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Params) GetPairs() []*Pair {
	if x != nil {
		if x.xxx_hidden_Pairs != nil {
			return *x.xxx_hidden_Pairs
		}
	}
	return nil
}

func (x *Params) SetPairs(v []*Pair) {
	x.xxx_hidden_Pairs = &v
}

type Params_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Параметры функции, представленные объектами с парами `название_параметра`—`значение_параметра`, которые будут служить модели примерами ожидаемого результата.
	Pairs []*Pair
}

func (b0 Params_builder) Build() *Params {
	m0 := &Params{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pairs = &b.Pairs
	return m0
}

// Параметры фукнции, сгенерированные моделью в формате `ключ-значение`.
type Pair struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Pair) Reset() {
	*x = Pair{}
	mi := &file_gigachatv1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Pair) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *Pair) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *Pair) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *Pair) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type Pair_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Название параметра
	Key string
	// Значение параметра
	Value string
}

func (b0 Pair_builder) Build() *Pair {
	m0 := &Pair{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

// Описывает сообщение, которое можно передавать в запросе.
type Message struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Role             string                 `protobuf:"bytes,1,opt,name=role,proto3"`
	xxx_hidden_Content          string                 `protobuf:"bytes,2,opt,name=content,proto3"`
	xxx_hidden_FunctionCall     *FunctionCall          `protobuf:"bytes,5,opt,name=function_call,json=functionCall,proto3,oneof"`
	xxx_hidden_FunctionName     *string                `protobuf:"bytes,6,opt,name=function_name,json=functionName,proto3,oneof"`
	xxx_hidden_FunctionsStateId *string                `protobuf:"bytes,8,opt,name=functions_state_id,json=functionsStateId,proto3,oneof"`
	xxx_hidden_Attachments      []string               `protobuf:"bytes,11,rep,name=attachments,proto3"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_gigachatv1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.xxx_hidden_Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return ""
}

func (x *Message) GetFunctionCall() *FunctionCall {
	if x != nil {
		return x.xxx_hidden_FunctionCall
	}
	return nil
}

func (x *Message) GetFunctionName() string {
	if x != nil {
		if x.xxx_hidden_FunctionName != nil {
			return *x.xxx_hidden_FunctionName
		}
		return ""
	}
	return ""
}

func (x *Message) GetFunctionsStateId() string {
	if x != nil {
		if x.xxx_hidden_FunctionsStateId != nil {
			return *x.xxx_hidden_FunctionsStateId
		}
		return ""
	}
	return ""
}

func (x *Message) GetAttachments() []string {
	if x != nil {
		return x.xxx_hidden_Attachments
	}
	return nil
}

func (x *Message) SetRole(v string) {
	x.xxx_hidden_Role = v
}

func (x *Message) SetContent(v string) {
	x.xxx_hidden_Content = v
}

func (x *Message) SetFunctionCall(v *FunctionCall) {
	x.xxx_hidden_FunctionCall = v
}

func (x *Message) SetFunctionName(v string) {
	x.xxx_hidden_FunctionName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *Message) SetFunctionsStateId(v string) {
	x.xxx_hidden_FunctionsStateId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Message) SetAttachments(v []string) {
	x.xxx_hidden_Attachments = v
}

func (x *Message) HasFunctionCall() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FunctionCall != nil
}

func (x *Message) HasFunctionName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Message) HasFunctionsStateId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Message) ClearFunctionCall() {
	x.xxx_hidden_FunctionCall = nil
}

func (x *Message) ClearFunctionName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_FunctionName = nil
}

func (x *Message) ClearFunctionsStateId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_FunctionsStateId = nil
}

type Message_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// *
	// Роль автора сообщения:
	// - `system` — системный промпт, который задает роль модели, например, должна модель отвечать как академик или как школьник;
	// - `assistant` — ответ модели;
	// - `user` — сообщение пользователя;
	// - `function` — сообщение с результатом работы пользовательской функции. В сообщении с этой ролью передавайте в поле `content` валидный JSON-объект с результатами работы функции.
	// Для сохранения контекста диалога с пользователем передайте несколько сообщений. Подробнее читайте в разделе [Работа с историей чата](/ru/gigachat/guides/keeping-context).
	Role string
	// *
	// Содержимое сообщения. Зависит от роли.
	// Если поле передается в сообщении с ролью `function`, то в нем указывается валидный JSON-объект с результатом выполнения функции.
	// В остальных случаях содержит либо системный промпт (сообщение с ролью `system`), либо текст сообщения пользователя или модели.
	Content      string
	FunctionCall *FunctionCall
	// Название функции, которое передается в сообщение с ролью `function`.
	FunctionName *string
	// *
	// Идентификатор, который объединяет массив функций, переданных в запросе.
	// Возвращается в ответе модели (сообщение с `"role": "assistant"`) если сообщение к модели содержало функции.
	// Позволяет сохранить контекст вызова функции и повысить качество работы модели.
	// Для этого нужно передать идентификатор в запросе на генерацию в сообщении с ролью `assistant`.
	FunctionsStateId *string
	// *
	// Массив идентификаторов файлов, которые нужно использовать при генерации.
	// Идентификатор присваивается файлу при загрузке в хранилище. Посмотреть список файлов в хранилище можно с помощью метода `GET /files`.
	// В одном запросе можно передать только одно изображение. В одной сессии можно передать до 10 изображений.
	// Подробнее — в разделе [Генерация с помощью файлов изображений](/ru/gigachat/guides/images-generation).
	Attachments []string
}

func (b0 Message_builder) Build() *Message {
	m0 := &Message{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Role = b.Role
	x.xxx_hidden_Content = b.Content
	x.xxx_hidden_FunctionCall = b.FunctionCall
	if b.FunctionName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_FunctionName = b.FunctionName
	}
	if b.FunctionsStateId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_FunctionsStateId = b.FunctionsStateId
	}
	x.xxx_hidden_Attachments = b.Attachments
	return m0
}

// Описание ответа модели.
type ChatResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alternatives *[]*Alternative        `protobuf:"bytes,1,rep,name=alternatives,proto3"`
	xxx_hidden_Usage        *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3"`
	xxx_hidden_ModelInfo    *ModelInfo             `protobuf:"bytes,3,opt,name=model_info,json=modelInfo,proto3"`
	xxx_hidden_Timestamp    int64                  `protobuf:"varint,4,opt,name=timestamp,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_gigachatv1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatResponse) GetAlternatives() []*Alternative {
	if x != nil {
		if x.xxx_hidden_Alternatives != nil {
			return *x.xxx_hidden_Alternatives
		}
	}
	return nil
}

func (x *ChatResponse) GetUsage() *Usage {
	if x != nil {
		return x.xxx_hidden_Usage
	}
	return nil
}

func (x *ChatResponse) GetModelInfo() *ModelInfo {
	if x != nil {
		return x.xxx_hidden_ModelInfo
	}
	return nil
}

func (x *ChatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *ChatResponse) SetAlternatives(v []*Alternative) {
	x.xxx_hidden_Alternatives = &v
}

func (x *ChatResponse) SetUsage(v *Usage) {
	x.xxx_hidden_Usage = v
}

func (x *ChatResponse) SetModelInfo(v *ModelInfo) {
	x.xxx_hidden_ModelInfo = v
}

func (x *ChatResponse) SetTimestamp(v int64) {
	x.xxx_hidden_Timestamp = v
}

func (x *ChatResponse) HasUsage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Usage != nil
}

func (x *ChatResponse) HasModelInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ModelInfo != nil
}

func (x *ChatResponse) ClearUsage() {
	x.xxx_hidden_Usage = nil
}

func (x *ChatResponse) ClearModelInfo() {
	x.xxx_hidden_ModelInfo = nil
}

type ChatResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alternatives []*Alternative
	// Данные об использовании модели.
	Usage *Usage
	// Данные о модели
	ModelInfo *ModelInfo
	// Время ответа.
	Timestamp int64
}

func (b0 ChatResponse_builder) Build() *ChatResponse {
	m0 := &ChatResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Alternatives = &b.Alternatives
	x.xxx_hidden_Usage = b.Usage
	x.xxx_hidden_ModelInfo = b.ModelInfo
	x.xxx_hidden_Timestamp = b.Timestamp
	return m0
}

// Сгенерированное сообщение.
type Alternative struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message      *Message               `protobuf:"bytes,1,opt,name=message,proto3"`
	xxx_hidden_FinishReason string                 `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3"`
	xxx_hidden_Index        int32                  `protobuf:"varint,3,opt,name=index,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Alternative) Reset() {
	*x = Alternative{}
	mi := &file_gigachatv1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alternative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alternative) ProtoMessage() {}

func (x *Alternative) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Alternative) GetMessage() *Message {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return nil
}

func (x *Alternative) GetFinishReason() string {
	if x != nil {
		return x.xxx_hidden_FinishReason
	}
	return ""
}

func (x *Alternative) GetIndex() int32 {
	if x != nil {
		return x.xxx_hidden_Index
	}
	return 0
}

func (x *Alternative) SetMessage(v *Message) {
	x.xxx_hidden_Message = v
}

func (x *Alternative) SetFinishReason(v string) {
	x.xxx_hidden_FinishReason = v
}

func (x *Alternative) SetIndex(v int32) {
	x.xxx_hidden_Index = v
}

func (x *Alternative) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *Alternative) ClearMessage() {
	x.xxx_hidden_Message = nil
}

type Alternative_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Message      *Message
	FinishReason string
	Index        int32
}

func (b0 Alternative_builder) Build() *Alternative {
	m0 := &Alternative{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Message = b.Message
	x.xxx_hidden_FinishReason = b.FinishReason
	x.xxx_hidden_Index = b.Index
	return m0
}

// Информация о количестве токенов, потраченных при генерации ответа.
type Usage struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3"`
	xxx_hidden_CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3"`
	xxx_hidden_TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_gigachatv1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.xxx_hidden_PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.xxx_hidden_CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.xxx_hidden_TotalTokens
	}
	return 0
}

func (x *Usage) SetPromptTokens(v int32) {
	x.xxx_hidden_PromptTokens = v
}

func (x *Usage) SetCompletionTokens(v int32) {
	x.xxx_hidden_CompletionTokens = v
}

func (x *Usage) SetTotalTokens(v int32) {
	x.xxx_hidden_TotalTokens = v
}

type Usage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Количество токенов во входящем сообщении (роль `user`)
	PromptTokens int32
	// Количество токенов, сгенерированных моделью (роль `assistant`)
	CompletionTokens int32
	// Общее количество токенов
	TotalTokens int32
}

func (b0 Usage_builder) Build() *Usage {
	m0 := &Usage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PromptTokens = b.PromptTokens
	x.xxx_hidden_CompletionTokens = b.CompletionTokens
	x.xxx_hidden_TotalTokens = b.TotalTokens
	return m0
}

// Информация о модели.
type ModelInfo struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name    string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Version string                 `protobuf:"bytes,2,opt,name=version,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_gigachatv1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ModelInfo) GetVersion() string {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return ""
}

func (x *ModelInfo) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ModelInfo) SetVersion(v string) {
	x.xxx_hidden_Version = v
}

type ModelInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Название модели.
	Name string
	// Версия модели. Подробнее о версиях — в разделе [Обновления моделей](/ru/gigachat/models/main).
	Version string
}

func (b0 ModelInfo_builder) Build() *ModelInfo {
	m0 := &ModelInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Version = b.Version
	return m0
}

// Сгенерированный моделью вызов функции.
type FunctionCall struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name      string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Arguments string                 `protobuf:"bytes,2,opt,name=arguments,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_gigachatv1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *FunctionCall) GetArguments() string {
	if x != nil {
		return x.xxx_hidden_Arguments
	}
	return ""
}

func (x *FunctionCall) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *FunctionCall) SetArguments(v string) {
	x.xxx_hidden_Arguments = v
}

type FunctionCall_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Название функции
	Name string
	// Аргументы функции. Содержат описание в JSON-формате.
	Arguments string
}

func (b0 FunctionCall_builder) Build() *FunctionCall {
	m0 := &FunctionCall{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Arguments = b.Arguments
	return m0
}

// Запрос списка доступных моделей.
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_gigachatv1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListModelsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListModelsRequest_builder) Build() *ListModelsRequest {
	m0 := &ListModelsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Список с описанием доступных моделей.
type ListModelsResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Models *[]*Model              `protobuf:"bytes,1,rep,name=models,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_gigachatv1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		if x.xxx_hidden_Models != nil {
			return *x.xxx_hidden_Models
		}
	}
	return nil
}

func (x *ListModelsResponse) SetModels(v []*Model) {
	x.xxx_hidden_Models = &v
}

type ListModelsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Models []*Model
}

func (b0 ListModelsResponse_builder) Build() *ListModelsResponse {
	m0 := &ListModelsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Models = &b.Models
	return m0
}

// Описание модели.
type Model struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name    string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Object  string                 `protobuf:"bytes,2,opt,name=object,proto3"`
	xxx_hidden_OwnedBy string                 `protobuf:"bytes,3,opt,name=owned_by,json=ownedBy,proto3"`
	xxx_hidden_Type    string                 `protobuf:"bytes,8,opt,name=type,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_gigachatv1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Model) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Model) GetObject() string {
	if x != nil {
		return x.xxx_hidden_Object
	}
	return ""
}

func (x *Model) GetOwnedBy() string {
	if x != nil {
		return x.xxx_hidden_OwnedBy
	}
	return ""
}

func (x *Model) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *Model) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Model) SetObject(v string) {
	x.xxx_hidden_Object = v
}

func (x *Model) SetOwnedBy(v string) {
	x.xxx_hidden_OwnedBy = v
}

func (x *Model) SetType(v string) {
	x.xxx_hidden_Type = v
}

type Model_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Название модели. Описание доступных моделей смотрите в разделе [Модели GigaChat](/ru/gigachat/models/main).
	// При обращении к моделям в раннем доступе к названию модели нужно добавлять постфикс `-preview`. Например, `GigaChat-Pro-preview`.
	Name string
	// Тип сущности в ответе, например, модель.
	Object string
	// Владелец модели.
	OwnedBy string
	// Тип модели. При запросах на генерацию передается тип `chat`.
	Type string
}

func (b0 Model_builder) Build() *Model {
	m0 := &Model{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Object = b.Object
	x.xxx_hidden_OwnedBy = b.OwnedBy
	x.xxx_hidden_Type = b.Type
	return m0
}

// Запрос модели по конкретному имени.
type RetrieveModelRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetrieveModelRequest) Reset() {
	*x = RetrieveModelRequest{}
	mi := &file_gigachatv1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveModelRequest) ProtoMessage() {}

func (x *RetrieveModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RetrieveModelRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *RetrieveModelRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

type RetrieveModelRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
}

func (b0 RetrieveModelRequest_builder) Build() *RetrieveModelRequest {
	m0 := &RetrieveModelRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

type RetrieveModelResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Model *Model                 `protobuf:"bytes,1,opt,name=model,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RetrieveModelResponse) Reset() {
	*x = RetrieveModelResponse{}
	mi := &file_gigachatv1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveModelResponse) ProtoMessage() {}

func (x *RetrieveModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gigachatv1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RetrieveModelResponse) GetModel() *Model {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return nil
}

func (x *RetrieveModelResponse) SetModel(v *Model) {
	x.xxx_hidden_Model = v
}

func (x *RetrieveModelResponse) HasModel() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Model != nil
}

func (x *RetrieveModelResponse) ClearModel() {
	x.xxx_hidden_Model = nil
}

type RetrieveModelResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Model *Model
}

func (b0 RetrieveModelResponse_builder) Build() *RetrieveModelResponse {
	m0 := &RetrieveModelResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Model = b.Model
	return m0
}

var File_gigachatv1_proto protoreflect.FileDescriptor

const file_gigachatv1_proto_rawDesc = "" +
	"\n" +
	"\x10gigachatv1.proto\x12\vgigachat.v1\"\x89\x01\n" +
	"\vChatRequest\x122\n" +
	"\aoptions\x18\x01 \x01(\v2\x18.gigachat.v1.ChatOptionsR\aoptions\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x120\n" +
	"\bmessages\x18\x03 \x03(\v2\x14.gigachat.v1.MessageR\bmessages\"\xbf\x03\n" +
	"\vChatOptions\x12%\n" +
	"\vtemperature\x18\x01 \x01(\x02H\x00R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\x02 \x01(\x02H\x01R\x04topP\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05H\x02R\tmaxTokens\x88\x01\x01\x122\n" +
	"\x12repetition_penalty\x18\x05 \x01(\x02H\x03R\x11repetitionPenalty\x88\x01\x01\x12,\n" +
	"\x0fupdate_interval\x18\x06 \x01(\x02H\x04R\x0eupdateInterval\x88\x01\x01\x12\x14\n" +
	"\x05flags\x18\a \x03(\tR\x05flags\x12D\n" +
	"\rfunction_call\x18\b \x01(\v2\x1f.gigachat.v1.FunctionCallPolicyR\ffunctionCall\x123\n" +
	"\tfunctions\x18\t \x03(\v2\x15.gigachat.v1.FunctionR\tfunctionsB\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_pB\r\n" +
	"\v_max_tokensB\x15\n" +
	"\x13_repetition_penaltyB\x12\n" +
	"\x10_update_intervalJ\x04\b\x03\x10\x04\"\xa7\x01\n" +
	"\x12FunctionCallPolicy\x128\n" +
	"\x04mode\x18\x01 \x01(\x0e2$.gigachat.v1.FunctionCallPolicy.ModeR\x04mode\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\"5\n" +
	"\x04Mode\x12\r\n" +
	"\tundefined\x10\x00\x12\b\n" +
	"\x04auto\x10\x01\x12\b\n" +
	"\x04none\x10\x02\x12\n" +
	"\n" +
	"\x06forced\x10\x03B\a\n" +
	"\x05_name\"\xed\x01\n" +
	"\bFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parameters\x12C\n" +
	"\x11few_shot_examples\x18\x04 \x03(\v2\x17.gigachat.v1.AnyExampleR\x0ffewShotExamples\x120\n" +
	"\x11return_parameters\x18\x05 \x01(\tH\x00R\x10returnParameters\x88\x01\x01B\x14\n" +
	"\x12_return_parameters\"S\n" +
	"\n" +
	"AnyExample\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\x12+\n" +
	"\x06params\x18\x02 \x01(\v2\x13.gigachat.v1.ParamsR\x06params\"1\n" +
	"\x06Params\x12'\n" +
	"\x05pairs\x18\x01 \x03(\v2\x11.gigachat.v1.PairR\x05pairs\".\n" +
	"\x04Pair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc2\x02\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12C\n" +
	"\rfunction_call\x18\x05 \x01(\v2\x19.gigachat.v1.FunctionCallH\x00R\ffunctionCall\x88\x01\x01\x12(\n" +
	"\rfunction_name\x18\x06 \x01(\tH\x01R\ffunctionName\x88\x01\x01\x121\n" +
	"\x12functions_state_id\x18\b \x01(\tH\x02R\x10functionsStateId\x88\x01\x01\x12 \n" +
	"\vattachments\x18\v \x03(\tR\vattachmentsB\x10\n" +
	"\x0e_function_callB\x10\n" +
	"\x0e_function_nameB\x15\n" +
	"\x13_functions_state_idJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"\xd1\x01\n" +
	"\fChatResponse\x12<\n" +
	"\falternatives\x18\x01 \x03(\v2\x18.gigachat.v1.AlternativeR\falternatives\x12(\n" +
	"\x05usage\x18\x02 \x01(\v2\x12.gigachat.v1.UsageR\x05usage\x125\n" +
	"\n" +
	"model_info\x18\x03 \x01(\v2\x16.gigachat.v1.ModelInfoR\tmodelInfo\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampJ\x04\b\x05\x10\x06\"x\n" +
	"\vAlternative\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.gigachat.v1.MessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x02 \x01(\tR\ffinishReason\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\"\x82\x01\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokensJ\x04\b\x04\x10\x05\"9\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"@\n" +
	"\fFunctionCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"\x13\n" +
	"\x11ListModelsRequest\"@\n" +
	"\x12ListModelsResponse\x12*\n" +
	"\x06models\x18\x01 \x03(\v2\x12.gigachat.v1.ModelR\x06models\"b\n" +
	"\x05Model\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x19\n" +
	"\bowned_by\x18\x03 \x01(\tR\aownedBy\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\"*\n" +
	"\x14RetrieveModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x15RetrieveModelResponse\x12(\n" +
	"\x05model\x18\x01 \x01(\v2\x12.gigachat.v1.ModelR\x05model2\x8f\x01\n" +
	"\vChatService\x12;\n" +
	"\x04Chat\x12\x18.gigachat.v1.ChatRequest\x1a\x19.gigachat.v1.ChatResponse\x12C\n" +
	"\n" +
	"ChatStream\x12\x18.gigachat.v1.ChatRequest\x1a\x19.gigachat.v1.ChatResponse0\x012\xb6\x01\n" +
	"\rModelsService\x12M\n" +
	"\n" +
	"ListModels\x12\x1e.gigachat.v1.ListModelsRequest\x1a\x1f.gigachat.v1.ListModelsResponse\x12V\n" +
	"\rRetrieveModel\x12!.gigachat.v1.RetrieveModelRequest\x1a\".gigachat.v1.RetrieveModelResponseB2Z0github.com/dmnAlex/sberscribe/pkg/api/gigachatv1b\x06proto3"

var file_gigachatv1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gigachatv1_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_gigachatv1_proto_goTypes = []any{
	(FunctionCallPolicy_Mode)(0),  // 0: gigachat.v1.FunctionCallPolicy.Mode
	(*ChatRequest)(nil),           // 1: gigachat.v1.ChatRequest
	(*ChatOptions)(nil),           // 2: gigachat.v1.ChatOptions
	(*FunctionCallPolicy)(nil),    // 3: gigachat.v1.FunctionCallPolicy
	(*Function)(nil),              // 4: gigachat.v1.Function
	(*AnyExample)(nil),            // 5: gigachat.v1.AnyExample
	(*Params)(nil),                // 6: gigachat.v1.Params
	(*Pair)(nil),                  // 7: gigachat.v1.Pair
	(*Message)(nil),               // 8: gigachat.v1.Message
	(*ChatResponse)(nil),          // 9: gigachat.v1.ChatResponse
	(*Alternative)(nil),           // 10: gigachat.v1.Alternative
	(*Usage)(nil),                 // 11: gigachat.v1.Usage
	(*ModelInfo)(nil),             // 12: gigachat.v1.ModelInfo
	(*FunctionCall)(nil),          // 13: gigachat.v1.FunctionCall
	(*ListModelsRequest)(nil),     // 14: gigachat.v1.ListModelsRequest
	(*ListModelsResponse)(nil),    // 15: gigachat.v1.ListModelsResponse
	(*Model)(nil),                 // 16: gigachat.v1.Model
	(*RetrieveModelRequest)(nil),  // 17: gigachat.v1.RetrieveModelRequest
	(*RetrieveModelResponse)(nil), // 18: gigachat.v1.RetrieveModelResponse
}
var file_gigachatv1_proto_depIdxs = []int32{
	2,  // 0: gigachat.v1.ChatRequest.options:type_name -> gigachat.v1.ChatOptions
	8,  // 1: gigachat.v1.ChatRequest.messages:type_name -> gigachat.v1.Message
	3,  // 2: gigachat.v1.ChatOptions.function_call:type_name -> gigachat.v1.FunctionCallPolicy
	4,  // 3: gigachat.v1.ChatOptions.functions:type_name -> gigachat.v1.Function
	0,  // 4: gigachat.v1.FunctionCallPolicy.mode:type_name -> gigachat.v1.FunctionCallPolicy.Mode
	5,  // 5: gigachat.v1.Function.few_shot_examples:type_name -> gigachat.v1.AnyExample
	6,  // 6: gigachat.v1.AnyExample.params:type_name -> gigachat.v1.Params
	7,  // 7: gigachat.v1.Params.pairs:type_name -> gigachat.v1.Pair
	13, // 8: gigachat.v1.Message.function_call:type_name -> gigachat.v1.FunctionCall
	10, // 9: gigachat.v1.ChatResponse.alternatives:type_name -> gigachat.v1.Alternative
	11, // 10: gigachat.v1.ChatResponse.usage:type_name -> gigachat.v1.Usage
	12, // 11: gigachat.v1.ChatResponse.model_info:type_name -> gigachat.v1.ModelInfo
	8,  // 12: gigachat.v1.Alternative.message:type_name -> gigachat.v1.Message
	16, // 13: gigachat.v1.ListModelsResponse.models:type_name -> gigachat.v1.Model
	16, // 14: gigachat.v1.RetrieveModelResponse.model:type_name -> gigachat.v1.Model
	1,  // 15: gigachat.v1.ChatService.Chat:input_type -> gigachat.v1.ChatRequest
	1,  // 16: gigachat.v1.ChatService.ChatStream:input_type -> gigachat.v1.ChatRequest
	14, // 17: gigachat.v1.ModelsService.ListModels:input_type -> gigachat.v1.ListModelsRequest
	17, // 18: gigachat.v1.ModelsService.RetrieveModel:input_type -> gigachat.v1.RetrieveModelRequest
	9,  // 19: gigachat.v1.ChatService.Chat:output_type -> gigachat.v1.ChatResponse
	9,  // 20: gigachat.v1.ChatService.ChatStream:output_type -> gigachat.v1.ChatResponse
	15, // 21: gigachat.v1.ModelsService.ListModels:output_type -> gigachat.v1.ListModelsResponse
	18, // 22: gigachat.v1.ModelsService.RetrieveModel:output_type -> gigachat.v1.RetrieveModelResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_gigachatv1_proto_init() }
func file_gigachatv1_proto_init() {
	if File_gigachatv1_proto != nil {
		return
	}
	file_gigachatv1_proto_msgTypes[1].OneofWrappers = []any{}
	file_gigachatv1_proto_msgTypes[2].OneofWrappers = []any{}
	file_gigachatv1_proto_msgTypes[3].OneofWrappers = []any{}
	file_gigachatv1_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gigachatv1_proto_rawDesc), len(file_gigachatv1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gigachatv1_proto_goTypes,
		DependencyIndexes: file_gigachatv1_proto_depIdxs,
		EnumInfos:         file_gigachatv1_proto_enumTypes,
		MessageInfos:      file_gigachatv1_proto_msgTypes,
	}.Build()
	File_gigachatv1_proto = out.File
	file_gigachatv1_proto_goTypes = nil
	file_gigachatv1_proto_depIdxs = nil
}
