// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: recognition.proto

package recognitionv1

import (
	taskv1 "github.com/dmnAlex/sberscribe/pkg/api/taskv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EouReason int32

const (
	EouReason_UNSPECIFIED        EouReason = 0 // Not an EOU
	EouReason_ORGANIC            EouReason = 1 // Proper EOU
	EouReason_NO_SPEECH_TIMEOUT  EouReason = 2 // EOU because there was no speech for at least no_speech_timeout seconds
	EouReason_MAX_SPEECH_TIMEOUT EouReason = 3 // EOU because there was continuous speech with no breaks for at least max_speech_timeout seconds
)

// Enum value maps for EouReason.
var (
	EouReason_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ORGANIC",
		2: "NO_SPEECH_TIMEOUT",
		3: "MAX_SPEECH_TIMEOUT",
	}
	EouReason_value = map[string]int32{
		"UNSPECIFIED":        0,
		"ORGANIC":            1,
		"NO_SPEECH_TIMEOUT":  2,
		"MAX_SPEECH_TIMEOUT": 3,
	}
)

func (x EouReason) Enum() *EouReason {
	p := new(EouReason)
	*p = x
	return p
}

func (x EouReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EouReason) Descriptor() protoreflect.EnumDescriptor {
	return file_recognition_proto_enumTypes[0].Descriptor()
}

func (EouReason) Type() protoreflect.EnumType {
	return &file_recognition_proto_enumTypes[0]
}

func (x EouReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type RecognitionOptions_AudioEncoding int32

const (
	RecognitionOptions_AUDIO_ENCODING_UNSPECIFIED RecognitionOptions_AudioEncoding = 0
	RecognitionOptions_PCM_S16LE                  RecognitionOptions_AudioEncoding = 1 // 16-bit signed little-endian (Linear PCM)
	RecognitionOptions_OPUS                       RecognitionOptions_AudioEncoding = 2 // mime audio/ogg; codecs=opus
	RecognitionOptions_MP3                        RecognitionOptions_AudioEncoding = 3 // MPEG-1/2 Layer-3
	RecognitionOptions_FLAC                       RecognitionOptions_AudioEncoding = 4
	RecognitionOptions_ALAW                       RecognitionOptions_AudioEncoding = 5
	RecognitionOptions_MULAW                      RecognitionOptions_AudioEncoding = 6
)

// Enum value maps for RecognitionOptions_AudioEncoding.
var (
	RecognitionOptions_AudioEncoding_name = map[int32]string{
		0: "AUDIO_ENCODING_UNSPECIFIED",
		1: "PCM_S16LE",
		2: "OPUS",
		3: "MP3",
		4: "FLAC",
		5: "ALAW",
		6: "MULAW",
	}
	RecognitionOptions_AudioEncoding_value = map[string]int32{
		"AUDIO_ENCODING_UNSPECIFIED": 0,
		"PCM_S16LE":                  1,
		"OPUS":                       2,
		"MP3":                        3,
		"FLAC":                       4,
		"ALAW":                       5,
		"MULAW":                      6,
	}
)

func (x RecognitionOptions_AudioEncoding) Enum() *RecognitionOptions_AudioEncoding {
	p := new(RecognitionOptions_AudioEncoding)
	*p = x
	return p
}

func (x RecognitionOptions_AudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecognitionOptions_AudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_recognition_proto_enumTypes[1].Descriptor()
}

func (RecognitionOptions_AudioEncoding) Type() protoreflect.EnumType {
	return &file_recognition_proto_enumTypes[1]
}

func (x RecognitionOptions_AudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type RecognitionRequest struct {
	state              protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Request isRecognitionRequest_Request `protobuf_oneof:"request"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecognitionRequest) Reset() {
	*x = RecognitionRequest{}
	mi := &file_recognition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionRequest) ProtoMessage() {}

func (x *RecognitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecognitionRequest) GetOptions() *RecognitionOptions {
	if x != nil {
		if x, ok := x.xxx_hidden_Request.(*recognitionRequest_Options); ok {
			return x.Options
		}
	}
	return nil
}

func (x *RecognitionRequest) GetAudioChunk() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Request.(*recognitionRequest_AudioChunk); ok {
			return x.AudioChunk
		}
	}
	return nil
}

func (x *RecognitionRequest) SetOptions(v *RecognitionOptions) {
	if v == nil {
		x.xxx_hidden_Request = nil
		return
	}
	x.xxx_hidden_Request = &recognitionRequest_Options{v}
}

func (x *RecognitionRequest) SetAudioChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Request = &recognitionRequest_AudioChunk{v}
}

func (x *RecognitionRequest) HasRequest() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Request != nil
}

func (x *RecognitionRequest) HasOptions() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Request.(*recognitionRequest_Options)
	return ok
}

func (x *RecognitionRequest) HasAudioChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Request.(*recognitionRequest_AudioChunk)
	return ok
}

func (x *RecognitionRequest) ClearRequest() {
	x.xxx_hidden_Request = nil
}

func (x *RecognitionRequest) ClearOptions() {
	if _, ok := x.xxx_hidden_Request.(*recognitionRequest_Options); ok {
		x.xxx_hidden_Request = nil
	}
}

func (x *RecognitionRequest) ClearAudioChunk() {
	if _, ok := x.xxx_hidden_Request.(*recognitionRequest_AudioChunk); ok {
		x.xxx_hidden_Request = nil
	}
}

const RecognitionRequest_Request_not_set_case case_RecognitionRequest_Request = 0
const RecognitionRequest_Options_case case_RecognitionRequest_Request = 1
const RecognitionRequest_AudioChunk_case case_RecognitionRequest_Request = 2

func (x *RecognitionRequest) WhichRequest() case_RecognitionRequest_Request {
	if x == nil {
		return RecognitionRequest_Request_not_set_case
	}
	switch x.xxx_hidden_Request.(type) {
	case *recognitionRequest_Options:
		return RecognitionRequest_Options_case
	case *recognitionRequest_AudioChunk:
		return RecognitionRequest_AudioChunk_case
	default:
		return RecognitionRequest_Request_not_set_case
	}
}

type RecognitionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Request:
	Options    *RecognitionOptions
	AudioChunk []byte
	// -- end of xxx_hidden_Request
}

func (b0 RecognitionRequest_builder) Build() *RecognitionRequest {
	m0 := &RecognitionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Options != nil {
		x.xxx_hidden_Request = &recognitionRequest_Options{b.Options}
	}
	if b.AudioChunk != nil {
		x.xxx_hidden_Request = &recognitionRequest_AudioChunk{b.AudioChunk}
	}
	return m0
}

type case_RecognitionRequest_Request protoreflect.FieldNumber

func (x case_RecognitionRequest_Request) String() string {
	md := file_recognition_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isRecognitionRequest_Request interface {
	isRecognitionRequest_Request()
}

type recognitionRequest_Options struct {
	Options *RecognitionOptions `protobuf:"bytes,1,opt,name=options,proto3,oneof"`
}

type recognitionRequest_AudioChunk struct {
	AudioChunk []byte `protobuf:"bytes,2,opt,name=audio_chunk,json=audioChunk,proto3,oneof"`
}

func (*recognitionRequest_Options) isRecognitionRequest_Request() {}

func (*recognitionRequest_AudioChunk) isRecognitionRequest_Request() {}

type RecognitionResponse struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Results             *[]*Hypothesis         `protobuf:"bytes,1,rep,name=results,proto3"`
	xxx_hidden_Eou                 bool                   `protobuf:"varint,2,opt,name=eou,proto3"`
	xxx_hidden_EmotionsResult      *Emotions              `protobuf:"bytes,3,opt,name=emotions_result,json=emotionsResult,proto3"`
	xxx_hidden_ProcessedAudioStart *durationpb.Duration   `protobuf:"bytes,4,opt,name=processed_audio_start,json=processedAudioStart,proto3"`
	xxx_hidden_ProcessedAudioEnd   *durationpb.Duration   `protobuf:"bytes,5,opt,name=processed_audio_end,json=processedAudioEnd,proto3"`
	xxx_hidden_BackendInfo         *BackendInfo           `protobuf:"bytes,6,opt,name=backend_info,json=backendInfo,proto3"`
	xxx_hidden_Channel             int32                  `protobuf:"varint,7,opt,name=channel,proto3"`
	xxx_hidden_SpeakerInfo         *SpeakerInfo           `protobuf:"bytes,8,opt,name=speaker_info,json=speakerInfo,proto3"`
	xxx_hidden_EouReason           EouReason              `protobuf:"varint,9,opt,name=eou_reason,json=eouReason,proto3,enum=smartspeech.recognition.v1.EouReason"`
	xxx_hidden_Insight             string                 `protobuf:"bytes,10,opt,name=insight,proto3"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *RecognitionResponse) Reset() {
	*x = RecognitionResponse{}
	mi := &file_recognition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionResponse) ProtoMessage() {}

func (x *RecognitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecognitionResponse) GetResults() []*Hypothesis {
	if x != nil {
		if x.xxx_hidden_Results != nil {
			return *x.xxx_hidden_Results
		}
	}
	return nil
}

func (x *RecognitionResponse) GetEou() bool {
	if x != nil {
		return x.xxx_hidden_Eou
	}
	return false
}

func (x *RecognitionResponse) GetEmotionsResult() *Emotions {
	if x != nil {
		return x.xxx_hidden_EmotionsResult
	}
	return nil
}

func (x *RecognitionResponse) GetProcessedAudioStart() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_ProcessedAudioStart
	}
	return nil
}

func (x *RecognitionResponse) GetProcessedAudioEnd() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_ProcessedAudioEnd
	}
	return nil
}

func (x *RecognitionResponse) GetBackendInfo() *BackendInfo {
	if x != nil {
		return x.xxx_hidden_BackendInfo
	}
	return nil
}

func (x *RecognitionResponse) GetChannel() int32 {
	if x != nil {
		return x.xxx_hidden_Channel
	}
	return 0
}

func (x *RecognitionResponse) GetSpeakerInfo() *SpeakerInfo {
	if x != nil {
		return x.xxx_hidden_SpeakerInfo
	}
	return nil
}

func (x *RecognitionResponse) GetEouReason() EouReason {
	if x != nil {
		return x.xxx_hidden_EouReason
	}
	return EouReason_UNSPECIFIED
}

func (x *RecognitionResponse) GetInsight() string {
	if x != nil {
		return x.xxx_hidden_Insight
	}
	return ""
}

func (x *RecognitionResponse) SetResults(v []*Hypothesis) {
	x.xxx_hidden_Results = &v
}

func (x *RecognitionResponse) SetEou(v bool) {
	x.xxx_hidden_Eou = v
}

func (x *RecognitionResponse) SetEmotionsResult(v *Emotions) {
	x.xxx_hidden_EmotionsResult = v
}

func (x *RecognitionResponse) SetProcessedAudioStart(v *durationpb.Duration) {
	x.xxx_hidden_ProcessedAudioStart = v
}

func (x *RecognitionResponse) SetProcessedAudioEnd(v *durationpb.Duration) {
	x.xxx_hidden_ProcessedAudioEnd = v
}

func (x *RecognitionResponse) SetBackendInfo(v *BackendInfo) {
	x.xxx_hidden_BackendInfo = v
}

func (x *RecognitionResponse) SetChannel(v int32) {
	x.xxx_hidden_Channel = v
}

func (x *RecognitionResponse) SetSpeakerInfo(v *SpeakerInfo) {
	x.xxx_hidden_SpeakerInfo = v
}

func (x *RecognitionResponse) SetEouReason(v EouReason) {
	x.xxx_hidden_EouReason = v
}

func (x *RecognitionResponse) SetInsight(v string) {
	x.xxx_hidden_Insight = v
}

func (x *RecognitionResponse) HasEmotionsResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EmotionsResult != nil
}

func (x *RecognitionResponse) HasProcessedAudioStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ProcessedAudioStart != nil
}

func (x *RecognitionResponse) HasProcessedAudioEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ProcessedAudioEnd != nil
}

func (x *RecognitionResponse) HasBackendInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BackendInfo != nil
}

func (x *RecognitionResponse) HasSpeakerInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SpeakerInfo != nil
}

func (x *RecognitionResponse) ClearEmotionsResult() {
	x.xxx_hidden_EmotionsResult = nil
}

func (x *RecognitionResponse) ClearProcessedAudioStart() {
	x.xxx_hidden_ProcessedAudioStart = nil
}

func (x *RecognitionResponse) ClearProcessedAudioEnd() {
	x.xxx_hidden_ProcessedAudioEnd = nil
}

func (x *RecognitionResponse) ClearBackendInfo() {
	x.xxx_hidden_BackendInfo = nil
}

func (x *RecognitionResponse) ClearSpeakerInfo() {
	x.xxx_hidden_SpeakerInfo = nil
}

type RecognitionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Results             []*Hypothesis
	Eou                 bool
	EmotionsResult      *Emotions
	ProcessedAudioStart *durationpb.Duration
	ProcessedAudioEnd   *durationpb.Duration
	BackendInfo         *BackendInfo
	Channel             int32
	SpeakerInfo         *SpeakerInfo
	EouReason           EouReason
	Insight             string
}

func (b0 RecognitionResponse_builder) Build() *RecognitionResponse {
	m0 := &RecognitionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Results = &b.Results
	x.xxx_hidden_Eou = b.Eou
	x.xxx_hidden_EmotionsResult = b.EmotionsResult
	x.xxx_hidden_ProcessedAudioStart = b.ProcessedAudioStart
	x.xxx_hidden_ProcessedAudioEnd = b.ProcessedAudioEnd
	x.xxx_hidden_BackendInfo = b.BackendInfo
	x.xxx_hidden_Channel = b.Channel
	x.xxx_hidden_SpeakerInfo = b.SpeakerInfo
	x.xxx_hidden_EouReason = b.EouReason
	x.xxx_hidden_Insight = b.Insight
	return m0
}

type AsyncRecognizeRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Options       *RecognitionOptions    `protobuf:"bytes,1,opt,name=options,proto3"`
	xxx_hidden_RequestFileId string                 `protobuf:"bytes,2,opt,name=request_file_id,json=requestFileId,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AsyncRecognizeRequest) Reset() {
	*x = AsyncRecognizeRequest{}
	mi := &file_recognition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncRecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncRecognizeRequest) ProtoMessage() {}

func (x *AsyncRecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AsyncRecognizeRequest) GetOptions() *RecognitionOptions {
	if x != nil {
		return x.xxx_hidden_Options
	}
	return nil
}

func (x *AsyncRecognizeRequest) GetRequestFileId() string {
	if x != nil {
		return x.xxx_hidden_RequestFileId
	}
	return ""
}

func (x *AsyncRecognizeRequest) SetOptions(v *RecognitionOptions) {
	x.xxx_hidden_Options = v
}

func (x *AsyncRecognizeRequest) SetRequestFileId(v string) {
	x.xxx_hidden_RequestFileId = v
}

func (x *AsyncRecognizeRequest) HasOptions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Options != nil
}

func (x *AsyncRecognizeRequest) ClearOptions() {
	x.xxx_hidden_Options = nil
}

type AsyncRecognizeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Options       *RecognitionOptions
	RequestFileId string
}

func (b0 AsyncRecognizeRequest_builder) Build() *AsyncRecognizeRequest {
	m0 := &AsyncRecognizeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Options = b.Options
	x.xxx_hidden_RequestFileId = b.RequestFileId
	return m0
}

type RecognitionOptions struct {
	state                               protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_AudioEncoding            RecognitionOptions_AudioEncoding `protobuf:"varint,1,opt,name=audio_encoding,json=audioEncoding,proto3,enum=smartspeech.recognition.v1.RecognitionOptions_AudioEncoding"`
	xxx_hidden_SampleRate               int32                            `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3"`
	xxx_hidden_Language                 string                           `protobuf:"bytes,3,opt,name=language,proto3"`
	xxx_hidden_Model                    string                           `protobuf:"bytes,4,opt,name=model,proto3"`
	xxx_hidden_HypothesesCount          int32                            `protobuf:"varint,5,opt,name=hypotheses_count,json=hypothesesCount,proto3"`
	xxx_hidden_Hints                    *Hints                           `protobuf:"bytes,6,opt,name=hints,proto3"`
	xxx_hidden_EnableProfanityFilter    bool                             `protobuf:"varint,7,opt,name=enable_profanity_filter,json=enableProfanityFilter,proto3"`
	xxx_hidden_EnableMultiUtterance     bool                             `protobuf:"varint,8,opt,name=enable_multi_utterance,json=enableMultiUtterance,proto3"`
	xxx_hidden_EnablePartialResults     bool                             `protobuf:"varint,9,opt,name=enable_partial_results,json=enablePartialResults,proto3"`
	xxx_hidden_NoSpeechTimeout          *durationpb.Duration             `protobuf:"bytes,10,opt,name=no_speech_timeout,json=noSpeechTimeout,proto3"`
	xxx_hidden_MaxSpeechTimeout         *durationpb.Duration             `protobuf:"bytes,11,opt,name=max_speech_timeout,json=maxSpeechTimeout,proto3"`
	xxx_hidden_ChannelsCount            int32                            `protobuf:"varint,12,opt,name=channels_count,json=channelsCount,proto3"`
	xxx_hidden_SpeakerSeparationOptions *SpeakerSeparationOptions        `protobuf:"bytes,13,opt,name=speaker_separation_options,json=speakerSeparationOptions,proto3"`
	xxx_hidden_InsightModels            []string                         `protobuf:"bytes,14,rep,name=insight_models,json=insightModels,proto3"`
	xxx_hidden_ForceCyrillic            bool                             `protobuf:"varint,15,opt,name=force_cyrillic,json=forceCyrillic,proto3"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *RecognitionOptions) Reset() {
	*x = RecognitionOptions{}
	mi := &file_recognition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognitionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionOptions) ProtoMessage() {}

func (x *RecognitionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecognitionOptions) GetAudioEncoding() RecognitionOptions_AudioEncoding {
	if x != nil {
		return x.xxx_hidden_AudioEncoding
	}
	return RecognitionOptions_AUDIO_ENCODING_UNSPECIFIED
}

func (x *RecognitionOptions) GetSampleRate() int32 {
	if x != nil {
		return x.xxx_hidden_SampleRate
	}
	return 0
}

func (x *RecognitionOptions) GetLanguage() string {
	if x != nil {
		return x.xxx_hidden_Language
	}
	return ""
}

func (x *RecognitionOptions) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *RecognitionOptions) GetHypothesesCount() int32 {
	if x != nil {
		return x.xxx_hidden_HypothesesCount
	}
	return 0
}

func (x *RecognitionOptions) GetHints() *Hints {
	if x != nil {
		return x.xxx_hidden_Hints
	}
	return nil
}

func (x *RecognitionOptions) GetEnableProfanityFilter() bool {
	if x != nil {
		return x.xxx_hidden_EnableProfanityFilter
	}
	return false
}

func (x *RecognitionOptions) GetEnableMultiUtterance() bool {
	if x != nil {
		return x.xxx_hidden_EnableMultiUtterance
	}
	return false
}

func (x *RecognitionOptions) GetEnablePartialResults() bool {
	if x != nil {
		return x.xxx_hidden_EnablePartialResults
	}
	return false
}

func (x *RecognitionOptions) GetNoSpeechTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_NoSpeechTimeout
	}
	return nil
}

func (x *RecognitionOptions) GetMaxSpeechTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_MaxSpeechTimeout
	}
	return nil
}

func (x *RecognitionOptions) GetChannelsCount() int32 {
	if x != nil {
		return x.xxx_hidden_ChannelsCount
	}
	return 0
}

func (x *RecognitionOptions) GetSpeakerSeparationOptions() *SpeakerSeparationOptions {
	if x != nil {
		return x.xxx_hidden_SpeakerSeparationOptions
	}
	return nil
}

func (x *RecognitionOptions) GetInsightModels() []string {
	if x != nil {
		return x.xxx_hidden_InsightModels
	}
	return nil
}

func (x *RecognitionOptions) GetForceCyrillic() bool {
	if x != nil {
		return x.xxx_hidden_ForceCyrillic
	}
	return false
}

func (x *RecognitionOptions) SetAudioEncoding(v RecognitionOptions_AudioEncoding) {
	x.xxx_hidden_AudioEncoding = v
}

func (x *RecognitionOptions) SetSampleRate(v int32) {
	x.xxx_hidden_SampleRate = v
}

func (x *RecognitionOptions) SetLanguage(v string) {
	x.xxx_hidden_Language = v
}

func (x *RecognitionOptions) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *RecognitionOptions) SetHypothesesCount(v int32) {
	x.xxx_hidden_HypothesesCount = v
}

func (x *RecognitionOptions) SetHints(v *Hints) {
	x.xxx_hidden_Hints = v
}

func (x *RecognitionOptions) SetEnableProfanityFilter(v bool) {
	x.xxx_hidden_EnableProfanityFilter = v
}

func (x *RecognitionOptions) SetEnableMultiUtterance(v bool) {
	x.xxx_hidden_EnableMultiUtterance = v
}

func (x *RecognitionOptions) SetEnablePartialResults(v bool) {
	x.xxx_hidden_EnablePartialResults = v
}

func (x *RecognitionOptions) SetNoSpeechTimeout(v *durationpb.Duration) {
	x.xxx_hidden_NoSpeechTimeout = v
}

func (x *RecognitionOptions) SetMaxSpeechTimeout(v *durationpb.Duration) {
	x.xxx_hidden_MaxSpeechTimeout = v
}

func (x *RecognitionOptions) SetChannelsCount(v int32) {
	x.xxx_hidden_ChannelsCount = v
}

func (x *RecognitionOptions) SetSpeakerSeparationOptions(v *SpeakerSeparationOptions) {
	x.xxx_hidden_SpeakerSeparationOptions = v
}

func (x *RecognitionOptions) SetInsightModels(v []string) {
	x.xxx_hidden_InsightModels = v
}

func (x *RecognitionOptions) SetForceCyrillic(v bool) {
	x.xxx_hidden_ForceCyrillic = v
}

func (x *RecognitionOptions) HasHints() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Hints != nil
}

func (x *RecognitionOptions) HasNoSpeechTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NoSpeechTimeout != nil
}

func (x *RecognitionOptions) HasMaxSpeechTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MaxSpeechTimeout != nil
}

func (x *RecognitionOptions) HasSpeakerSeparationOptions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SpeakerSeparationOptions != nil
}

func (x *RecognitionOptions) ClearHints() {
	x.xxx_hidden_Hints = nil
}

func (x *RecognitionOptions) ClearNoSpeechTimeout() {
	x.xxx_hidden_NoSpeechTimeout = nil
}

func (x *RecognitionOptions) ClearMaxSpeechTimeout() {
	x.xxx_hidden_MaxSpeechTimeout = nil
}

func (x *RecognitionOptions) ClearSpeakerSeparationOptions() {
	x.xxx_hidden_SpeakerSeparationOptions = nil
}

type RecognitionOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AudioEncoding            RecognitionOptions_AudioEncoding
	SampleRate               int32
	Language                 string
	Model                    string
	HypothesesCount          int32
	Hints                    *Hints
	EnableProfanityFilter    bool
	EnableMultiUtterance     bool
	EnablePartialResults     bool
	NoSpeechTimeout          *durationpb.Duration
	MaxSpeechTimeout         *durationpb.Duration
	ChannelsCount            int32
	SpeakerSeparationOptions *SpeakerSeparationOptions
	InsightModels            []string
	ForceCyrillic            bool
}

func (b0 RecognitionOptions_builder) Build() *RecognitionOptions {
	m0 := &RecognitionOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AudioEncoding = b.AudioEncoding
	x.xxx_hidden_SampleRate = b.SampleRate
	x.xxx_hidden_Language = b.Language
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_HypothesesCount = b.HypothesesCount
	x.xxx_hidden_Hints = b.Hints
	x.xxx_hidden_EnableProfanityFilter = b.EnableProfanityFilter
	x.xxx_hidden_EnableMultiUtterance = b.EnableMultiUtterance
	x.xxx_hidden_EnablePartialResults = b.EnablePartialResults
	x.xxx_hidden_NoSpeechTimeout = b.NoSpeechTimeout
	x.xxx_hidden_MaxSpeechTimeout = b.MaxSpeechTimeout
	x.xxx_hidden_ChannelsCount = b.ChannelsCount
	x.xxx_hidden_SpeakerSeparationOptions = b.SpeakerSeparationOptions
	x.xxx_hidden_InsightModels = b.InsightModels
	x.xxx_hidden_ForceCyrillic = b.ForceCyrillic
	return m0
}

type Hints struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Words         []string               `protobuf:"bytes,1,rep,name=words,proto3"`
	xxx_hidden_EnableLetters bool                   `protobuf:"varint,2,opt,name=enable_letters,json=enableLetters,proto3"`
	xxx_hidden_EouTimeout    *durationpb.Duration   `protobuf:"bytes,3,opt,name=eou_timeout,json=eouTimeout,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Hints) Reset() {
	*x = Hints{}
	mi := &file_recognition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hints) ProtoMessage() {}

func (x *Hints) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Hints) GetWords() []string {
	if x != nil {
		return x.xxx_hidden_Words
	}
	return nil
}

func (x *Hints) GetEnableLetters() bool {
	if x != nil {
		return x.xxx_hidden_EnableLetters
	}
	return false
}

func (x *Hints) GetEouTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_EouTimeout
	}
	return nil
}

func (x *Hints) SetWords(v []string) {
	x.xxx_hidden_Words = v
}

func (x *Hints) SetEnableLetters(v bool) {
	x.xxx_hidden_EnableLetters = v
}

func (x *Hints) SetEouTimeout(v *durationpb.Duration) {
	x.xxx_hidden_EouTimeout = v
}

func (x *Hints) HasEouTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EouTimeout != nil
}

func (x *Hints) ClearEouTimeout() {
	x.xxx_hidden_EouTimeout = nil
}

type Hints_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Words         []string
	EnableLetters bool
	EouTimeout    *durationpb.Duration
}

func (b0 Hints_builder) Build() *Hints {
	m0 := &Hints{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Words = b.Words
	x.xxx_hidden_EnableLetters = b.EnableLetters
	x.xxx_hidden_EouTimeout = b.EouTimeout
	return m0
}

type SpeakerSeparationOptions struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enable                bool                   `protobuf:"varint,1,opt,name=enable,proto3"`
	xxx_hidden_EnableOnlyMainSpeaker bool                   `protobuf:"varint,2,opt,name=enable_only_main_speaker,json=enableOnlyMainSpeaker,proto3"`
	xxx_hidden_Count                 int32                  `protobuf:"varint,3,opt,name=count,proto3"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *SpeakerSeparationOptions) Reset() {
	*x = SpeakerSeparationOptions{}
	mi := &file_recognition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakerSeparationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakerSeparationOptions) ProtoMessage() {}

func (x *SpeakerSeparationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SpeakerSeparationOptions) GetEnable() bool {
	if x != nil {
		return x.xxx_hidden_Enable
	}
	return false
}

func (x *SpeakerSeparationOptions) GetEnableOnlyMainSpeaker() bool {
	if x != nil {
		return x.xxx_hidden_EnableOnlyMainSpeaker
	}
	return false
}

func (x *SpeakerSeparationOptions) GetCount() int32 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *SpeakerSeparationOptions) SetEnable(v bool) {
	x.xxx_hidden_Enable = v
}

func (x *SpeakerSeparationOptions) SetEnableOnlyMainSpeaker(v bool) {
	x.xxx_hidden_EnableOnlyMainSpeaker = v
}

func (x *SpeakerSeparationOptions) SetCount(v int32) {
	x.xxx_hidden_Count = v
}

type SpeakerSeparationOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Enable                bool
	EnableOnlyMainSpeaker bool
	Count                 int32
}

func (b0 SpeakerSeparationOptions_builder) Build() *SpeakerSeparationOptions {
	m0 := &SpeakerSeparationOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Enable = b.Enable
	x.xxx_hidden_EnableOnlyMainSpeaker = b.EnableOnlyMainSpeaker
	x.xxx_hidden_Count = b.Count
	return m0
}

type Hypothesis struct {
	state                     protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Text           string                       `protobuf:"bytes,1,opt,name=text,proto3"`
	xxx_hidden_NormalizedText string                       `protobuf:"bytes,2,opt,name=normalized_text,json=normalizedText,proto3"`
	xxx_hidden_Start          *durationpb.Duration         `protobuf:"bytes,3,opt,name=start,proto3"`
	xxx_hidden_End            *durationpb.Duration         `protobuf:"bytes,4,opt,name=end,proto3"`
	xxx_hidden_WordAlignments *[]*Hypothesis_WordAlignment `protobuf:"bytes,5,rep,name=word_alignments,json=wordAlignments,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Hypothesis) Reset() {
	*x = Hypothesis{}
	mi := &file_recognition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hypothesis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hypothesis) ProtoMessage() {}

func (x *Hypothesis) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Hypothesis) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *Hypothesis) GetNormalizedText() string {
	if x != nil {
		return x.xxx_hidden_NormalizedText
	}
	return ""
}

func (x *Hypothesis) GetStart() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return nil
}

func (x *Hypothesis) GetEnd() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_End
	}
	return nil
}

func (x *Hypothesis) GetWordAlignments() []*Hypothesis_WordAlignment {
	if x != nil {
		if x.xxx_hidden_WordAlignments != nil {
			return *x.xxx_hidden_WordAlignments
		}
	}
	return nil
}

func (x *Hypothesis) SetText(v string) {
	x.xxx_hidden_Text = v
}

func (x *Hypothesis) SetNormalizedText(v string) {
	x.xxx_hidden_NormalizedText = v
}

func (x *Hypothesis) SetStart(v *durationpb.Duration) {
	x.xxx_hidden_Start = v
}

func (x *Hypothesis) SetEnd(v *durationpb.Duration) {
	x.xxx_hidden_End = v
}

func (x *Hypothesis) SetWordAlignments(v []*Hypothesis_WordAlignment) {
	x.xxx_hidden_WordAlignments = &v
}

func (x *Hypothesis) HasStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Start != nil
}

func (x *Hypothesis) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *Hypothesis) ClearStart() {
	x.xxx_hidden_Start = nil
}

func (x *Hypothesis) ClearEnd() {
	x.xxx_hidden_End = nil
}

type Hypothesis_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Text           string
	NormalizedText string
	Start          *durationpb.Duration
	End            *durationpb.Duration
	WordAlignments []*Hypothesis_WordAlignment
}

func (b0 Hypothesis_builder) Build() *Hypothesis {
	m0 := &Hypothesis{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Text = b.Text
	x.xxx_hidden_NormalizedText = b.NormalizedText
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	x.xxx_hidden_WordAlignments = &b.WordAlignments
	return m0
}

type Emotions struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Positive float32                `protobuf:"fixed32,1,opt,name=positive,proto3"`
	xxx_hidden_Neutral  float32                `protobuf:"fixed32,2,opt,name=neutral,proto3"`
	xxx_hidden_Negative float32                `protobuf:"fixed32,3,opt,name=negative,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Emotions) Reset() {
	*x = Emotions{}
	mi := &file_recognition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emotions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emotions) ProtoMessage() {}

func (x *Emotions) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Emotions) GetPositive() float32 {
	if x != nil {
		return x.xxx_hidden_Positive
	}
	return 0
}

func (x *Emotions) GetNeutral() float32 {
	if x != nil {
		return x.xxx_hidden_Neutral
	}
	return 0
}

func (x *Emotions) GetNegative() float32 {
	if x != nil {
		return x.xxx_hidden_Negative
	}
	return 0
}

func (x *Emotions) SetPositive(v float32) {
	x.xxx_hidden_Positive = v
}

func (x *Emotions) SetNeutral(v float32) {
	x.xxx_hidden_Neutral = v
}

func (x *Emotions) SetNegative(v float32) {
	x.xxx_hidden_Negative = v
}

type Emotions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Positive float32
	Neutral  float32
	Negative float32
}

func (b0 Emotions_builder) Build() *Emotions {
	m0 := &Emotions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Positive = b.Positive
	x.xxx_hidden_Neutral = b.Neutral
	x.xxx_hidden_Negative = b.Negative
	return m0
}

type BackendInfo struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3"`
	xxx_hidden_ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3"`
	xxx_hidden_ServerVersion string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BackendInfo) Reset() {
	*x = BackendInfo{}
	mi := &file_recognition_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendInfo) ProtoMessage() {}

func (x *BackendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BackendInfo) GetModelName() string {
	if x != nil {
		return x.xxx_hidden_ModelName
	}
	return ""
}

func (x *BackendInfo) GetModelVersion() string {
	if x != nil {
		return x.xxx_hidden_ModelVersion
	}
	return ""
}

func (x *BackendInfo) GetServerVersion() string {
	if x != nil {
		return x.xxx_hidden_ServerVersion
	}
	return ""
}

func (x *BackendInfo) SetModelName(v string) {
	x.xxx_hidden_ModelName = v
}

func (x *BackendInfo) SetModelVersion(v string) {
	x.xxx_hidden_ModelVersion = v
}

func (x *BackendInfo) SetServerVersion(v string) {
	x.xxx_hidden_ServerVersion = v
}

type BackendInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ModelName     string
	ModelVersion  string
	ServerVersion string
}

func (b0 BackendInfo_builder) Build() *BackendInfo {
	m0 := &BackendInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ModelName = b.ModelName
	x.xxx_hidden_ModelVersion = b.ModelVersion
	x.xxx_hidden_ServerVersion = b.ServerVersion
	return m0
}

type SpeakerInfo struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SpeakerId             int32                  `protobuf:"varint,1,opt,name=speaker_id,json=speakerId,proto3"`
	xxx_hidden_MainSpeakerConfidence float32                `protobuf:"fixed32,2,opt,name=main_speaker_confidence,json=mainSpeakerConfidence,proto3"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *SpeakerInfo) Reset() {
	*x = SpeakerInfo{}
	mi := &file_recognition_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakerInfo) ProtoMessage() {}

func (x *SpeakerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SpeakerInfo) GetSpeakerId() int32 {
	if x != nil {
		return x.xxx_hidden_SpeakerId
	}
	return 0
}

func (x *SpeakerInfo) GetMainSpeakerConfidence() float32 {
	if x != nil {
		return x.xxx_hidden_MainSpeakerConfidence
	}
	return 0
}

func (x *SpeakerInfo) SetSpeakerId(v int32) {
	x.xxx_hidden_SpeakerId = v
}

func (x *SpeakerInfo) SetMainSpeakerConfidence(v float32) {
	x.xxx_hidden_MainSpeakerConfidence = v
}

type SpeakerInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SpeakerId             int32
	MainSpeakerConfidence float32
}

func (b0 SpeakerInfo_builder) Build() *SpeakerInfo {
	m0 := &SpeakerInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SpeakerId = b.SpeakerId
	x.xxx_hidden_MainSpeakerConfidence = b.MainSpeakerConfidence
	return m0
}

type Hypothesis_WordAlignment struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Word  string                 `protobuf:"bytes,1,opt,name=word,proto3"`
	xxx_hidden_Start *durationpb.Duration   `protobuf:"bytes,2,opt,name=start,proto3"`
	xxx_hidden_End   *durationpb.Duration   `protobuf:"bytes,3,opt,name=end,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Hypothesis_WordAlignment) Reset() {
	*x = Hypothesis_WordAlignment{}
	mi := &file_recognition_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hypothesis_WordAlignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hypothesis_WordAlignment) ProtoMessage() {}

func (x *Hypothesis_WordAlignment) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Hypothesis_WordAlignment) GetWord() string {
	if x != nil {
		return x.xxx_hidden_Word
	}
	return ""
}

func (x *Hypothesis_WordAlignment) GetStart() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return nil
}

func (x *Hypothesis_WordAlignment) GetEnd() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_End
	}
	return nil
}

func (x *Hypothesis_WordAlignment) SetWord(v string) {
	x.xxx_hidden_Word = v
}

func (x *Hypothesis_WordAlignment) SetStart(v *durationpb.Duration) {
	x.xxx_hidden_Start = v
}

func (x *Hypothesis_WordAlignment) SetEnd(v *durationpb.Duration) {
	x.xxx_hidden_End = v
}

func (x *Hypothesis_WordAlignment) HasStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Start != nil
}

func (x *Hypothesis_WordAlignment) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *Hypothesis_WordAlignment) ClearStart() {
	x.xxx_hidden_Start = nil
}

func (x *Hypothesis_WordAlignment) ClearEnd() {
	x.xxx_hidden_End = nil
}

type Hypothesis_WordAlignment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Word  string
	Start *durationpb.Duration
	End   *durationpb.Duration
}

func (b0 Hypothesis_WordAlignment_builder) Build() *Hypothesis_WordAlignment {
	m0 := &Hypothesis_WordAlignment{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Word = b.Word
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	return m0
}

var File_recognition_proto protoreflect.FileDescriptor

const file_recognition_proto_rawDesc = "" +
	"\n" +
	"\x11recognition.proto\x12\x1asmartspeech.recognition.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\n" +
	"task.proto\"\x8e\x01\n" +
	"\x12RecognitionRequest\x12J\n" +
	"\aoptions\x18\x01 \x01(\v2..smartspeech.recognition.v1.RecognitionOptionsH\x00R\aoptions\x12!\n" +
	"\vaudio_chunk\x18\x02 \x01(\fH\x00R\n" +
	"audioChunkB\t\n" +
	"\arequest\"\xe4\x04\n" +
	"\x13RecognitionResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.smartspeech.recognition.v1.HypothesisR\aresults\x12\x10\n" +
	"\x03eou\x18\x02 \x01(\bR\x03eou\x12M\n" +
	"\x0femotions_result\x18\x03 \x01(\v2$.smartspeech.recognition.v1.EmotionsR\x0eemotionsResult\x12M\n" +
	"\x15processed_audio_start\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x13processedAudioStart\x12I\n" +
	"\x13processed_audio_end\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x11processedAudioEnd\x12J\n" +
	"\fbackend_info\x18\x06 \x01(\v2'.smartspeech.recognition.v1.BackendInfoR\vbackendInfo\x12\x18\n" +
	"\achannel\x18\a \x01(\x05R\achannel\x12J\n" +
	"\fspeaker_info\x18\b \x01(\v2'.smartspeech.recognition.v1.SpeakerInfoR\vspeakerInfo\x12D\n" +
	"\n" +
	"eou_reason\x18\t \x01(\x0e2%.smartspeech.recognition.v1.EouReasonR\teouReason\x12\x18\n" +
	"\ainsight\x18\n" +
	" \x01(\tR\ainsight\"\x89\x01\n" +
	"\x15AsyncRecognizeRequest\x12H\n" +
	"\aoptions\x18\x01 \x01(\v2..smartspeech.recognition.v1.RecognitionOptionsR\aoptions\x12&\n" +
	"\x0frequest_file_id\x18\x02 \x01(\tR\rrequestFileId\"\xbf\a\n" +
	"\x12RecognitionOptions\x12c\n" +
	"\x0eaudio_encoding\x18\x01 \x01(\x0e2<.smartspeech.recognition.v1.RecognitionOptions.AudioEncodingR\raudioEncoding\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12)\n" +
	"\x10hypotheses_count\x18\x05 \x01(\x05R\x0fhypothesesCount\x127\n" +
	"\x05hints\x18\x06 \x01(\v2!.smartspeech.recognition.v1.HintsR\x05hints\x126\n" +
	"\x17enable_profanity_filter\x18\a \x01(\bR\x15enableProfanityFilter\x124\n" +
	"\x16enable_multi_utterance\x18\b \x01(\bR\x14enableMultiUtterance\x124\n" +
	"\x16enable_partial_results\x18\t \x01(\bR\x14enablePartialResults\x12E\n" +
	"\x11no_speech_timeout\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x0fnoSpeechTimeout\x12G\n" +
	"\x12max_speech_timeout\x18\v \x01(\v2\x19.google.protobuf.DurationR\x10maxSpeechTimeout\x12%\n" +
	"\x0echannels_count\x18\f \x01(\x05R\rchannelsCount\x12r\n" +
	"\x1aspeaker_separation_options\x18\r \x01(\v24.smartspeech.recognition.v1.SpeakerSeparationOptionsR\x18speakerSeparationOptions\x12%\n" +
	"\x0einsight_models\x18\x0e \x03(\tR\rinsightModels\x12%\n" +
	"\x0eforce_cyrillic\x18\x0f \x01(\bR\rforceCyrillic\"p\n" +
	"\rAudioEncoding\x12\x1e\n" +
	"\x1aAUDIO_ENCODING_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPCM_S16LE\x10\x01\x12\b\n" +
	"\x04OPUS\x10\x02\x12\a\n" +
	"\x03MP3\x10\x03\x12\b\n" +
	"\x04FLAC\x10\x04\x12\b\n" +
	"\x04ALAW\x10\x05\x12\t\n" +
	"\x05MULAW\x10\x06\"\x80\x01\n" +
	"\x05Hints\x12\x14\n" +
	"\x05words\x18\x01 \x03(\tR\x05words\x12%\n" +
	"\x0eenable_letters\x18\x02 \x01(\bR\renableLetters\x12:\n" +
	"\veou_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"eouTimeout\"\x81\x01\n" +
	"\x18SpeakerSeparationOptions\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x127\n" +
	"\x18enable_only_main_speaker\x18\x02 \x01(\bR\x15enableOnlyMainSpeaker\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\x8a\x03\n" +
	"\n" +
	"Hypothesis\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12'\n" +
	"\x0fnormalized_text\x18\x02 \x01(\tR\x0enormalizedText\x12/\n" +
	"\x05start\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x05start\x12+\n" +
	"\x03end\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x03end\x12]\n" +
	"\x0fword_alignments\x18\x05 \x03(\v24.smartspeech.recognition.v1.Hypothesis.WordAlignmentR\x0ewordAlignments\x1a\x81\x01\n" +
	"\rWordAlignment\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12/\n" +
	"\x05start\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05start\x12+\n" +
	"\x03end\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03end\"\\\n" +
	"\bEmotions\x12\x1a\n" +
	"\bpositive\x18\x01 \x01(\x02R\bpositive\x12\x18\n" +
	"\aneutral\x18\x02 \x01(\x02R\aneutral\x12\x1a\n" +
	"\bnegative\x18\x03 \x01(\x02R\bnegative\"x\n" +
	"\vBackendInfo\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\"d\n" +
	"\vSpeakerInfo\x12\x1d\n" +
	"\n" +
	"speaker_id\x18\x01 \x01(\x05R\tspeakerId\x126\n" +
	"\x17main_speaker_confidence\x18\x02 \x01(\x02R\x15mainSpeakerConfidence*X\n" +
	"\tEouReason\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aORGANIC\x10\x01\x12\x15\n" +
	"\x11NO_SPEECH_TIMEOUT\x10\x02\x12\x16\n" +
	"\x12MAX_SPEECH_TIMEOUT\x10\x032\xdf\x01\n" +
	"\vSmartSpeech\x12p\n" +
	"\tRecognize\x12..smartspeech.recognition.v1.RecognitionRequest\x1a/.smartspeech.recognition.v1.RecognitionResponse(\x010\x01\x12^\n" +
	"\x0eAsyncRecognize\x121.smartspeech.recognition.v1.AsyncRecognizeRequest\x1a\x19.smartspeech.task.v1.TaskB;\n" +
	"\x04TODOZ3github.com/dmnAlex/sberscribe/pkg/api/recognitionv1b\x06proto3"

var file_recognition_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_recognition_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_recognition_proto_goTypes = []any{
	(EouReason)(0),                        // 0: smartspeech.recognition.v1.EouReason
	(RecognitionOptions_AudioEncoding)(0), // 1: smartspeech.recognition.v1.RecognitionOptions.AudioEncoding
	(*RecognitionRequest)(nil),            // 2: smartspeech.recognition.v1.RecognitionRequest
	(*RecognitionResponse)(nil),           // 3: smartspeech.recognition.v1.RecognitionResponse
	(*AsyncRecognizeRequest)(nil),         // 4: smartspeech.recognition.v1.AsyncRecognizeRequest
	(*RecognitionOptions)(nil),            // 5: smartspeech.recognition.v1.RecognitionOptions
	(*Hints)(nil),                         // 6: smartspeech.recognition.v1.Hints
	(*SpeakerSeparationOptions)(nil),      // 7: smartspeech.recognition.v1.SpeakerSeparationOptions
	(*Hypothesis)(nil),                    // 8: smartspeech.recognition.v1.Hypothesis
	(*Emotions)(nil),                      // 9: smartspeech.recognition.v1.Emotions
	(*BackendInfo)(nil),                   // 10: smartspeech.recognition.v1.BackendInfo
	(*SpeakerInfo)(nil),                   // 11: smartspeech.recognition.v1.SpeakerInfo
	(*Hypothesis_WordAlignment)(nil),      // 12: smartspeech.recognition.v1.Hypothesis.WordAlignment
	(*durationpb.Duration)(nil),           // 13: google.protobuf.Duration
	(*taskv1.Task)(nil),                   // 14: smartspeech.task.v1.Task
}
var file_recognition_proto_depIdxs = []int32{
	5,  // 0: smartspeech.recognition.v1.RecognitionRequest.options:type_name -> smartspeech.recognition.v1.RecognitionOptions
	8,  // 1: smartspeech.recognition.v1.RecognitionResponse.results:type_name -> smartspeech.recognition.v1.Hypothesis
	9,  // 2: smartspeech.recognition.v1.RecognitionResponse.emotions_result:type_name -> smartspeech.recognition.v1.Emotions
	13, // 3: smartspeech.recognition.v1.RecognitionResponse.processed_audio_start:type_name -> google.protobuf.Duration
	13, // 4: smartspeech.recognition.v1.RecognitionResponse.processed_audio_end:type_name -> google.protobuf.Duration
	10, // 5: smartspeech.recognition.v1.RecognitionResponse.backend_info:type_name -> smartspeech.recognition.v1.BackendInfo
	11, // 6: smartspeech.recognition.v1.RecognitionResponse.speaker_info:type_name -> smartspeech.recognition.v1.SpeakerInfo
	0,  // 7: smartspeech.recognition.v1.RecognitionResponse.eou_reason:type_name -> smartspeech.recognition.v1.EouReason
	5,  // 8: smartspeech.recognition.v1.AsyncRecognizeRequest.options:type_name -> smartspeech.recognition.v1.RecognitionOptions
	1,  // 9: smartspeech.recognition.v1.RecognitionOptions.audio_encoding:type_name -> smartspeech.recognition.v1.RecognitionOptions.AudioEncoding
	6,  // 10: smartspeech.recognition.v1.RecognitionOptions.hints:type_name -> smartspeech.recognition.v1.Hints
	13, // 11: smartspeech.recognition.v1.RecognitionOptions.no_speech_timeout:type_name -> google.protobuf.Duration
	13, // 12: smartspeech.recognition.v1.RecognitionOptions.max_speech_timeout:type_name -> google.protobuf.Duration
	7,  // 13: smartspeech.recognition.v1.RecognitionOptions.speaker_separation_options:type_name -> smartspeech.recognition.v1.SpeakerSeparationOptions
	13, // 14: smartspeech.recognition.v1.Hints.eou_timeout:type_name -> google.protobuf.Duration
	13, // 15: smartspeech.recognition.v1.Hypothesis.start:type_name -> google.protobuf.Duration
	13, // 16: smartspeech.recognition.v1.Hypothesis.end:type_name -> google.protobuf.Duration
	12, // 17: smartspeech.recognition.v1.Hypothesis.word_alignments:type_name -> smartspeech.recognition.v1.Hypothesis.WordAlignment
	13, // 18: smartspeech.recognition.v1.Hypothesis.WordAlignment.start:type_name -> google.protobuf.Duration
	13, // 19: smartspeech.recognition.v1.Hypothesis.WordAlignment.end:type_name -> google.protobuf.Duration
	2,  // 20: smartspeech.recognition.v1.SmartSpeech.Recognize:input_type -> smartspeech.recognition.v1.RecognitionRequest
	4,  // 21: smartspeech.recognition.v1.SmartSpeech.AsyncRecognize:input_type -> smartspeech.recognition.v1.AsyncRecognizeRequest
	3,  // 22: smartspeech.recognition.v1.SmartSpeech.Recognize:output_type -> smartspeech.recognition.v1.RecognitionResponse
	14, // 23: smartspeech.recognition.v1.SmartSpeech.AsyncRecognize:output_type -> smartspeech.task.v1.Task
	22, // [22:24] is the sub-list for method output_type
	20, // [20:22] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_recognition_proto_init() }
func file_recognition_proto_init() {
	if File_recognition_proto != nil {
		return
	}
	file_recognition_proto_msgTypes[0].OneofWrappers = []any{
		(*recognitionRequest_Options)(nil),
		(*recognitionRequest_AudioChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recognition_proto_rawDesc), len(file_recognition_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recognition_proto_goTypes,
		DependencyIndexes: file_recognition_proto_depIdxs,
		EnumInfos:         file_recognition_proto_enumTypes,
		MessageInfos:      file_recognition_proto_msgTypes,
	}.Build()
	File_recognition_proto = out.File
	file_recognition_proto_goTypes = nil
	file_recognition_proto_depIdxs = nil
}
